Repository ponylang/release-notes-bot-action, pull requests merged in 2022-07, with the labels that each got.

#33 Update to work with newer versions of git
  .release-notes/cranky-git.md
  entrypoint.py
Labels: changelog - fixed, discuss during sync

#35 Update base image
  .release-notes/new-alpine.md
  Dockerfile
Labels: changelog - changed, discuss during sync

#36 Fix pylint errors
  entrypoint.py
Labels: discuss during sync
